### ISSUE TITLE
bench/data is too big

### ISSUE THREAD

**Issue by Alberdi** [nomasystems/nbson#18]
Adding `nbson` as dependency takes around 200MB due to the bench/data folder being 105MB (+96MB of `.git/objects`).

Maybe we could swap these files with a script that uses https://github.com/nomasystems/nbson_corpus to generate them on demand (I don't know how long do that take).

After finding any solution to that, and here is the tricky part, the big files would remain in the repository even if we remove them in a newer commit. Removing any trace of them isn't hard, but that would change the references of all the commits in this repository, something that it's not ideal. Even then, if we're going that route, the sooner, the better.

**Comment by LoisSotoLopez** [comment]
Yes, we talked a while ago about this and the decided strategy was to separate the benchmarking on [a different repo](https://github.com/nomasystems/nbson_bench) (private right now). You might want to take a look at it.

**Comment by Alberdi** [comment]
https://github.com/nomasystems/nbson_bench is now ready to be published.

Once that's done, we could either:
1. Rewrite the history here to remove all the references to the big files.
2. Delete them in the last commit.

The first option might bring issues with the locked references in other projects (they can be easily solved with a `rebar3 upgrade nbson`), the second option leaves us with a repository 200MB bigger than it should.

I'd rather do the first one.

**Comment by LoisSotoLopez** [comment]
Yes, I find the first one more appropriate too. Removing that extra size seems reasonable to wipe out history.

**Comment by Alberdi** [comment]
A new proposal:
1. Rewrite the history on `main` to get rid of all references to the big files.
2. Release a new version with just that change so the users can update to it.
3. Keep a `main_old` branch with the current content of `main`, so the commits don't get lost.
4. In a few months (?) delete the `main_old` branch to free the space.

**Comment by Alberdi** [comment]
Done! Now if you go to an old commit in the `main` branch you won't see the big files:
https://github.com/nomasystems/nbson/tree/8e09db3c6a08efc61e791a85eb0bc10a994446b9/bench/data

But the equivalent from the `main_old` still has the same files with the same old shas:
https://github.com/nomasystems/nbson/tree/c49ee0d275f06b0436f1ffe52ba94481f56c7b96/bench/data
